export const translations = {
  en: {
    welcomeBack: "Welcome back",
    priceRange: "Price Range",
    brand: "Brand",
    viewMore: "View More ▼",
    viewLess: "View Less ▲",
    rating: "Rating",
    andAbove: "and above",
    sortBy: "Sort By",
    select: "-- Select --",
    priceLowHigh: "Price: Low to High",
    priceHighLow: "Price: High to Low",
    newest: "Newest",
    bestsellers: "Bestsellers",
    prev: "Prev",
    next: "Next",
    yourCart: "Your Cart",
    customersAlsoBought: "Customers Also Bought",
    pleaseLoginToViewCart: "Please log in to view your cart.",
  },
  hi: {
    welcomeBack: "वापसी पर स्वागत है",
    priceRange: "मूल्य सीमा",
    brand: "ब्रांड",
    viewMore: "और देखें ▼",
    viewLess: "कम देखें ▲",
    rating: "रेटिंग",
    andAbove: "या उससे अधिक",
    sortBy: "क्रमबद्ध करें",
    select: "-- चुनें --",
    priceLowHigh: "कीमत: कम से ज्यादा",
    priceHighLow: "कीमत: ज्यादा से कम",
    newest: "नवीनतम",
    bestsellers: "सर्वाधिक बिकने वाले",
    prev: "पिछला",
    next: "अगला",
  },
};
